version: '3.8'

services:
  backup-system:
    build: .
    container_name: backup-system
    environment:
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
    volumes:
      - ./BackupSettings.json:/app/BackupSettings.json
      - ./Backups:/app/Backups
      - ./logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: